### ISSUE TITLE
paths of copied system fonts are incorrect when `satyrographos install -system-font-prefix` runs

### ISSUE THREAD

**Issue by matonix** [na4zagin3/satyrographos#72]
(Written in Japanese only.)

## Problem 

`satyrographos install -system-font-prefix` コマンドでインストールされるフォントのディレクトリと fonts.satysfi-hash に記入されるディレクトリが異なっています。

フォントファイルそのものは `dist/fonts/system/<font file name>` に追加され、fonts.satysfi-hash に記入されるファイルパスは `dist/<font file name>` となっています。

以下は `satyrographos install -system-font-prefix` 実行後のディレクトリ構造です。

```
$ tree .satysfi -d
.satysfi
└── dist
    ├── fonts
    │   └── system
    ├── hash
    ├── hyph
    ├── md
    ├── packages
    └── unidata
```

## Environment

- satyrographos version 0.0.2.1
- SATySFi version 0.0.3
- macOS Mojave 10.14.6

**Comment by na4zagin3** [comment]
Thanks a lot! Fixed by #73.
